[package]
name = "tiauth"
version = "0.2.0"
authors = ["Tip ten Brink <75669206+tiptenbrink@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redb = "2.1.1"
opaque-borink = "0.4.0"
rand = "0.8"
hex = "0.4.3"
rmp = "0.8"
rmp-serde = "1.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
terrors = "=0.3.0"
base64 = "0.22.1"
openssl = "0.10"

[dev-dependencies]
tempfile = "3"