[package]
name = "tiauth"
version = "0.2.0"
authors = ["Tip ten Brink <75669206+tiptenbrink@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redb = "2.1.1"
opaque-borink = "0.3.7"
rand = "0.7"
hex = "0.4.3"


serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }


