[package]
name = "tiauth-app"
version = "0.2.0"
edition = "2021"

[dependencies]
tiauth-core = { path = "../tiauth-core" }
tiauth-server = { path = "../tiauth-server", features = ["functions"] }
redb = "2.1.1"
axum = "0.7.5"
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"] }
rand = "0.8"
terrors = "=0.3.0"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12.5", features = ["default", "json"] }
opaque-borink = "0.4.0"
