from tiauth_app_py.model import Claims, ClaimsBytes, Session

class ProofKey: ...

class ApplicationLogin: ...

class ApplicationRegister: ...

class ServerClient:
    def __new__(cls, application: str, private_key_pem: str, proof_expiration: int | None = None): ...

    def prepare_register(self, user_id: str, set_claims: Claims | ClaimsBytes | None = None) -> ApplicationRegister: ...

    def prepare_login(self, user_id: str, all_claims: bool | None = None, requested_claims: list[str] | None = None) -> ApplicationLogin: ...

class UserClient:
    def __new__(cls, application: str, tiauth_url: str): ...

    def register_user(self, app_register: ApplicationRegister, password: str): ...

    def login_user(self, app_login: ApplicationLogin, password: str) -> Session: ...