from tiauth_app_py.model import Claims, ClaimsBytes, ClaimsProof, ReadAllProof, ReadRangeProof, ReadSomeProof, Session

class ProofKey: ...

class ProofToken: ...

class ApplicationLogin: ...

class ApplicationRegister: ...

class AppClient:
    def __new__(cls, application: str, tiauth_url: str, private_key_pem: str, proof_expiration: int | None = None) -> None: ...

    def prepare_register(self, user_id: str) -> ApplicationRegister: ...

    def prepare_login(self, user_id: str, all_claims: bool | None = None, requested_claims: list[str] | None = None) -> ApplicationLogin: ...

class UserClient:
    def __new__(cls, application: str, tiauth_url: str) -> None: ...

    def register_user(self, app_register: ApplicationRegister, password: str) -> None: ...

    def login_user(self, app_login: ApplicationLogin, password: str) -> Session: ...

def proof_token_from_bytes(token: bytes) -> ProofToken: ...

def create_private_key_pem() -> str: ...

def public_from_private_key_pem(private_key_pem: str) -> str: ...

def load_key_from_pem(private_key_pem: str) -> ProofKey: ...

def create_set_claims_proof(application: str, key: ProofKey, token: ProofToken, user_id: str, claims: Claims | ClaimsBytes) -> str: ...

# def create_reset_proof(application: str, key: ProofKey, user_id: str) -> ClaimsProof: ...

def create_read_all_proof(application: str, key: ProofKey, token: ProofToken) -> ReadAllProof: ...

# def create_read_some_proof(application: str, key: ProofKey, selection: list[str]) -> ReadSomeProof: ...

# def create_read_range_proof(application: str, key: ProofKey, selection: list[str]) -> ReadRangeProof: ...