
name: Test
on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout rustfrc
      uses: actions/checkout@v2
    - name: Run deployment
      run: ./deployment/deploy.sh
    - name: Run test
      run: ./test.sh
